# 01 머신러닝 개념

- 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법을 통칭  
- 금융 사기 거래 적발하는 프로그램/스팸 메일 필터링  
- 데이터 마이닝, 영상 인식, 음성 인식, 자연어 처리 같이 난이도와 개발 복잡도가 높아지는 분야에서 머신러닝이 급속하게 발전을 이룸 

## 머신러닝의 분류

1. 지도학습
- 분류  
- 회귀  
- 추천 시스템  
- 시각/음성 감지/인지  
- 텍스트 분석,NLP

2. 비지도학습  
- 클러스터링  
- 차원 축소  
- 강화학습

## 넘파이

In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [3]:
array2=np.array([[1,2,3],
                [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [4]:
array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1:{:0}차원,array2:{:1}차원,array3:{:2}차원'.\
      format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원,array2:2차원,array3: 2차원


In [6]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [7]:
list2=[1,2,'test']
print(type(list2))
array2=np.array(list2)
print(type(array2))
print(array2,array2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' 'test'] <U11


In [8]:
list3=[1,2,3.0]
print(type(list3))
array3=np.array(list3)
print(type(array3))
print(array3,array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1. 2. 3.] float64


In [9]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

[1. 2. 3.] float64


In [10]:
array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

[1 2 3] int32


In [11]:
array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1 2 3] int32


In [12]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [13]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [14]:
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [15]:
array1=np.arange(10)
print('array1:\n',array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [16]:
array2=array1.reshape(2,5)
print('array2:\n',array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
array3=array1.reshape(5,2)
print('array3:\n',array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [19]:
array1.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [ ]:
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)

In [ ]:
array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

In [ ]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

In [ ]:
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

In [ ]:
array1=np.arange(1,10)
print('array1',array1)
value=array1[2]
print('value:',value)
print(type(value))

In [ ]:
print('맨 뒤의 값:', array1[-1],'맨 뒤에서 두 번째 값:', array1[-2])

In [20]:
array1=np.arange(1,10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [21]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())

array2d[[0,1],2]=> [3, 6]


In [22]:
array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array2d[[0,1],0:2]=> [[1, 2], [4, 5]]


In [23]:
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [24]:
org_array=np.array([3,1,5,9])
print('원본 행렬:',org_array)
sort_array1=np.sort(org_array)
print('np.sort( )호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort( )호출 후 원본 행렬:',org_array)

원본 행렬: [3 1 5 9]
np.sort( )호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( )호출 후 원본 행렬: [3 1 5 9]


In [25]:
sort_array2=org_array.sort()
print('org_array.sort( )호출 후 반환된 정렬 행렬:',sort_array2)
print('org_array.sort( )호출 후 원본 행렬:',org_array)

org_array.sort( )호출 후 반환된 정렬 행렬: None
org_array.sort( )호출 후 원본 행렬: [1 3 5 9]


In [26]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [27]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [28]:
A=np.array([[1,2,3],
           [4,5,6]])
B=np.array([[7,8],
           [9,10],
           [11,12]])

In [29]:
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [30]:
A=np.array([[1,2],
           [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


## 판다스

In [31]:
import pandas as pd

In [32]:
titanic=pd.read_csv("titanic_train.csv")

In [33]:
titanic.shape

(891, 12)

In [34]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [35]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [36]:
value_counts=titanic['Pclass'].value_counts()
value_counts

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [37]:
col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)

In [38]:
array1

array([1, 2, 3])

In [39]:
array1.shape

(3,)

In [40]:
df_list1=pd.DataFrame(list1,columns=col_name1)

In [41]:
df_list1

col1
0     1
1     2
2     3

In [42]:
df_array1=pd.DataFrame(array1,columns=col_name1)

In [43]:
df_array1

col1
0     1
1     2
2     3

2차원

In [44]:
col_name2=['col1','col2','col3']
list2=[[1,2,3],[11,12,13]]
array2=np.array(list2)

In [45]:
array2

array([[ 1,  2,  3],
       [11, 12, 13]])

In [46]:
array2.shape

(2, 3)

In [47]:
df_list2=pd.DataFrame(list2,columns=col_name2)

In [48]:
df_list2

col1  col2  col3
0     1     2     3
1    11    12    13

In [50]:
df_array2=pd.DataFrame(array2,columns=col_name2)

In [51]:
df_array2

col1  col2  col3
0     1     2     3
1    11    12    13

In [52]:
dict={'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict=pd.DataFrame(dict)
df_dict

col1  col2  col3
0     1     2     3
1    11    22    33

In [54]:
array3=df_dict.values
array3

array([[ 1,  2,  3],
       [11, 22, 33]], dtype=int64)

In [55]:
list3=df_dict.values.tolist()
list3

[[1, 2, 3], [11, 22, 33]]

In [56]:
dict3=df_dict.to_dict('list')
dict3

{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

In [57]:
titanic['Age_0']=0

In [58]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  
0        0         A/5 21171   7.2500   NaN        S      0  
1        0          PC 17599  71.2833   C85        C      0  
2        0  STON/O2. 3101282   7.9250   NaN        S      0  
3        0            113803  53.1000  C123        S      0  
4        0            373450   8.0500   NaN        S      0  
..     ...               ...      ...   ...      ...    ...  
886      0            211536  13.0000   NaN        S      0  
887      0            112053  30.0000   B42        S      0  
888      2        W./C. 6607  23.4500   NaN        S      0  
889      0            111369  30.0000  C148        C      0  
890      0            370376   7.7500   NaN        Q      0  

[891 rows x 13 columns]

In [61]:
titanic['Age_by_10']=titanic['Age']*10
titanic['Family_No']=titanic['SibSp']+titanic['Parch']+1
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0        0         A/5 21171   7.2500   NaN        S      0      220.0   
1        0          PC 17599  71.2833   C85        C      0      380.0   
2        0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   
3        0            113803  53.1000  C123        S      0      350.0   
4        0            373450   8.0500   NaN        S      0      350.0   
..     ...               ...      ...   ...      ...    ...        ...   
886      0            211536  13.0000   NaN        S      0      270.0   
887      0            112053  30.0000   B42        S      0      190.0   
888      2        W./C. 6607  23.4500   NaN        S      0        NaN   
889      0            111369  30.0000  C148        C      0      260.0   
890      0            370376   7.7500   NaN        Q      0      320.0   

     Family_No  
0            2  
1            2  
2            1  
3            2  
4            1  
..         ...  
886          1  
887          1  
888          4  
889          1  
890          1  

[891 rows x 15 columns]

In [62]:
titanic['Age_by_10']=titanic['Age_by_10']+100
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0        0         A/5 21171   7.2500   NaN        S      0      320.0   
1        0          PC 17599  71.2833   C85        C      0      480.0   
2        0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   
3        0            113803  53.1000  C123        S      0      450.0   
4        0            373450   8.0500   NaN        S      0      450.0   
..     ...               ...      ...   ...      ...    ...        ...   
886      0            211536  13.0000   NaN        S      0      370.0   
887      0            112053  30.0000   B42        S      0      290.0   
888      2        W./C. 6607  23.4500   NaN        S      0        NaN   
889      0            111369  30.0000  C148        C      0      360.0   
890      0            370376   7.7500   NaN        Q      0      420.0   

     Family_No  
0            2  
1            2  
2            1  
3            2  
4            1  
..         ...  
886          1  
887          1  
888          4  
889          1  
890          1  

[891 rows x 15 columns]

In [63]:
titanic_drop=titanic.drop('Age_0',axis=1)
titanic_drop

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0        0         A/5 21171   7.2500   NaN        S      320.0          2  
1        0          PC 17599  71.2833   C85        C      480.0          2  
2        0  STON/O2. 3101282   7.9250   NaN        S      360.0          1  
3        0            113803  53.1000  C123        S      450.0          2  
4        0            373450   8.0500   NaN        S      450.0          1  
..     ...               ...      ...   ...      ...        ...        ...  
886      0            211536  13.0000   NaN        S      370.0          1  
887      0            112053  30.0000   B42        S      290.0          1  
888      2        W./C. 6607  23.4500   NaN        S        NaN          4  
889      0            111369  30.0000  C148        C      360.0          1  
890      0            370376   7.7500   NaN        Q      420.0          1  

[891 rows x 14 columns]

In [64]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0        0         A/5 21171   7.2500   NaN        S      0      320.0   
1        0          PC 17599  71.2833   C85        C      0      480.0   
2        0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   
3        0            113803  53.1000  C123        S      0      450.0   
4        0            373450   8.0500   NaN        S      0      450.0   
..     ...               ...      ...   ...      ...    ...        ...   
886      0            211536  13.0000   NaN        S      0      370.0   
887      0            112053  30.0000   B42        S      0      290.0   
888      2        W./C. 6607  23.4500   NaN        S      0        NaN   
889      0            111369  30.0000  C148        C      0      360.0   
890      0            370376   7.7500   NaN        Q      0      420.0   

     Family_No  
0            2  
1            2  
2            1  
3            2  
4            1  
..         ...  
886          1  
887          1  
888          4  
889          1  
890          1  

[891 rows x 15 columns]

In [65]:
drop_result=titanic.drop(['Age_0','Age_by_10','Family_No'],axis=1,inplace=True)
drop_result

In [66]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [67]:
titanic=pd.read_csv("titanic_train.csv")

In [68]:
index=titanic.index

In [70]:
index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [71]:
index[0]=5

TypeError: Index does not support mutable operations

In [72]:
titanic_reset=titanic.reset_index(inplace=False)
titanic_reset

index  PassengerId  Survived  Pclass  \
0        0            1         0       3   
1        1            2         1       1   
2        2            3         1       3   
3        3            4         1       1   
4        4            5         0       3   
..     ...          ...       ...     ...   
886    886          887         0       2   
887    887          888         1       1   
888    888          889         0       3   
889    889          890         1       1   
890    890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 13 columns]

In [73]:
titanic['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [74]:
titanic[['Survived','Pclass']]

Survived  Pclass
0           0       3
1           1       1
2           1       3
3           1       1
4           0       3
..        ...     ...
886         0       2
887         1       1
888         0       3
889         1       1
890         0       3

[891 rows x 2 columns]

In [75]:
titanic[0]

KeyError: 0

In [76]:
titanic[0:3]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [77]:
titanic[titanic['Pclass']==3]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
2              3         1       3                    Heikkinen, Miss. Laina   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
5      male   NaN      0      0            330877   8.4583   NaN        Q  
7      male   2.0      3      1            349909  21.0750   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
882  female  22.0      0      0              7552  10.5167   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[491 rows x 12 columns]

In [78]:
data={'Name':['Chulmin','Eunkyung','Jinwoong','Soobeom'],
     'Year':[2011,2016,2015,2015],
     'Gender':['Male','Female','Male','Male']
     }
data_df=pd.DataFrame(data,index=['one','two','three','four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [80]:
data_df.iloc[0,0]

'Chulmin'

In [81]:
data_df.iloc[0,'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [83]:
data_df.loc['one','Name']

'Chulmin'

In [84]:
titanic[titanic['Age']>60]

PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
483          484         1       3                     Turkula, Mrs. (Hedwig)   
493          494         0       1                    Artagaveytia, Mr. Ramon   
545          546         0       1               Nicholson, Mr. Arthur Ernest   
555          556         0       1                         Wright, Mr. George   
570          571         1       2                         Harris, Mr. George   
625          626         0       1                      Sutton, Mr. Frederick   
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2                Mitchell, Mr. Henry Michael   
745          746         0       1               Crosby, Capt. Edward Gifford   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   
851          852         0       3                        Svensson, Mr. Johan   

        Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked  
33     male  66.0      0      0   C.A. 24579   10.5000          NaN        S  
54     male  65.0      0      1       113509   61.9792          B30        C  
96     male  71.0      0      0     PC 17754   34.6542           A5        C  
116    male  70.5      0      0       370369    7.7500          NaN        Q  
170    male  61.0      0      0       111240   33.5000          B19        S  
252    male  62.0      0      0       113514   26.5500          C87        S  
275  female  63.0      1      0        13502   77.9583           D7        S  
280    male  65.0      0      0       336439    7.7500          NaN        Q  
326    male  61.0      0      0       345364    6.2375          NaN        S  
438    male  64.0      1      4        19950  263.0000  C23 C25 C27        S  
456    male  65.0      0      0        13509   26.5500          E38        S  
483  female  63.0      0      0         4134    9.5875          NaN        S  
493    male  71.0      0      0     PC 17609   49.5042          NaN        C  
545    male  64.0      0      0          693   26.0000          NaN        S  
555    male  62.0      0      0       113807   26.5500          NaN        S  
570    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S  
625    male  61.0      0      0        36963   32.3208          D50        S  
630    male  80.0      0      0        27042   30.0000          A23        S  
672    male  70.0      0      0   C.A. 24580   10.5000          NaN        S  
745    male  70.0      1      1    WE/P 5735   71.0000          B22        S  
829  female  62.0      0      0       113572   80.0000          B28      NaN  
851    male  74.0      0      0       347060    7.7750          NaN        S

In [86]:
titanic[titanic['Age']>60][['Name','Age']]

Name   Age
33                       Wheadon, Mr. Edward H  66.0
54              Ostby, Mr. Engelhart Cornelius  65.0
96                   Goldschmidt, Mr. George B  71.0
116                       Connors, Mr. Patrick  70.5
170                  Van der hoef, Mr. Wyckoff  61.0
252                  Stead, Mr. William Thomas  62.0
275          Andrews, Miss. Kornelia Theodosia  63.0
280                           Duane, Mr. Frank  65.0
326                  Nysveen, Mr. Johan Hansen  61.0
438                          Fortune, Mr. Mark  64.0
456                  Millet, Mr. Francis Davis  65.0
483                     Turkula, Mrs. (Hedwig)  63.0
493                    Artagaveytia, Mr. Ramon  71.0
545               Nicholson, Mr. Arthur Ernest  64.0
555                         Wright, Mr. George  62.0
570                         Harris, Mr. George  62.0
625                      Sutton, Mr. Frederick  61.0
630       Barkworth, Mr. Algernon Henry Wilson  80.0
672                Mitchell, Mr. Henry Michael  70.0
745               Crosby, Capt. Edward Gifford  70.0
829  Stone, Mrs. George Nelson (Martha Evelyn)  62.0
851                        Svensson, Mr. Johan  74.0

In [87]:
titanic.loc[titanic['Age']>60,['Name','Age']]

Name   Age
33                       Wheadon, Mr. Edward H  66.0
54              Ostby, Mr. Engelhart Cornelius  65.0
96                   Goldschmidt, Mr. George B  71.0
116                       Connors, Mr. Patrick  70.5
170                  Van der hoef, Mr. Wyckoff  61.0
252                  Stead, Mr. William Thomas  62.0
275          Andrews, Miss. Kornelia Theodosia  63.0
280                           Duane, Mr. Frank  65.0
326                  Nysveen, Mr. Johan Hansen  61.0
438                          Fortune, Mr. Mark  64.0
456                  Millet, Mr. Francis Davis  65.0
483                     Turkula, Mrs. (Hedwig)  63.0
493                    Artagaveytia, Mr. Ramon  71.0
545               Nicholson, Mr. Arthur Ernest  64.0
555                         Wright, Mr. George  62.0
570                         Harris, Mr. George  62.0
625                      Sutton, Mr. Frederick  61.0
630       Barkworth, Mr. Algernon Henry Wilson  80.0
672                Mitchell, Mr. Henry Michael  70.0
745               Crosby, Capt. Edward Gifford  70.0
829  Stone, Mrs. George Nelson (Martha Evelyn)  62.0
851                        Svensson, Mr. Johan  74.0

In [91]:
titanic[(titanic['Age']>60)&(titanic['Pclass']==1)&(titanic['Sex']=='female')]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
880      1            230433  26.0000   NaN        S  
882      0              7552  10.5167   NaN        S  
885      5            382652  29.1250   NaN        Q  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  

[326 rows x 12 columns]

In [93]:
titanic_sorted=titanic.sort_values(by=['Name'])

In [94]:
titanic_sorted

PassengerId  Survived  Pclass                                   Name  \
845          846         0       3                    Abbing, Mr. Anthony   
746          747         0       3            Abbott, Mr. Rossmore Edward   
279          280         1       3       Abbott, Mrs. Stanton (Rosa Hunt)   
308          309         0       2                    Abelson, Mr. Samuel   
874          875         1       2  Abelson, Mrs. Samuel (Hannah Wizosky)   
..           ...       ...     ...                                    ...   
286          287         1       3                de Mulder, Mr. Theodore   
282          283         0       3              de Pelsmaeker, Mr. Alfons   
361          362         0       2              del Carlo, Mr. Sebastiano   
153          154         0       3        van Billiard, Mr. Austin Blyler   
868          869         0       3            van Melkebeke, Mr. Philemon   

        Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
845    male  42.0      0      0      C.A. 5547   7.5500   NaN        S  
746    male  16.0      1      1      C.A. 2673  20.2500   NaN        S  
279  female  35.0      1      1      C.A. 2673  20.2500   NaN        S  
308    male  30.0      1      0      P/PP 3381  24.0000   NaN        C  
874  female  28.0      1      0      P/PP 3381  24.0000   NaN        C  
..      ...   ...    ...    ...            ...      ...   ...      ...  
286    male  30.0      0      0         345774   9.5000   NaN        S  
282    male  16.0      0      0         345778   9.5000   NaN        S  
361    male  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C  
153    male  40.5      0      2       A/5. 851  14.5000   NaN        S  
868    male   NaN      0      0         345777   9.5000   NaN        S  

[891 rows x 12 columns]

In [95]:
titanic_sorted=titanic.sort_values(by=['Pclass','Name'],ascending=False)

In [96]:
titanic_sorted

PassengerId  Survived  Pclass  \
868          869         0       3   
153          154         0       3   
282          283         0       3   
286          287         1       3   
559          560         1       3   
..           ...       ...     ...   
460          461         1       1   
498          499         0       1   
297          298         0       1   
305          306         1       1   
730          731         1       1   

                                                Name     Sex    Age  SibSp  \
868                      van Melkebeke, Mr. Philemon    male    NaN      0   
153                  van Billiard, Mr. Austin Blyler    male  40.50      0   
282                        de Pelsmaeker, Mr. Alfons    male  16.00      0   
286                          de Mulder, Mr. Theodore    male  30.00      0   
559     de Messemaeker, Mrs. Guillaume Joseph (Emma)  female  36.00      1   
..                                               ...     ...    ...    ...   
460                              Anderson, Mr. Harry    male  48.00      0   
498  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00      1   
297                     Allison, Miss. Helen Loraine  female   2.00      1   
305                   Allison, Master. Hudson Trevor    male   0.92      1   
730                    Allen, Miss. Elisabeth Walton  female  29.00      0   

     Parch    Ticket      Fare    Cabin Embarked  
868      0    345777    9.5000      NaN        S  
153      2  A/5. 851   14.5000      NaN        S  
282      0    345778    9.5000      NaN        S  
286      0    345774    9.5000      NaN        S  
559      0    345572   17.4000      NaN        S  
..     ...       ...       ...      ...      ...  
460      0     19952   26.5500      E12        S  
498      2    113781  151.5500  C22 C26        S  
297      2    113781  151.5500  C22 C26        S  
305      2    113781  151.5500  C22 C26        S  
730      0     24160  211.3375       B5        S  

[891 rows x 12 columns]

In [97]:
titanic.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [98]:
titanic[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [101]:
titanic.groupby(by='Pclass').count()

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216   
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491

In [102]:
titanic.groupby(by='Pclass')['Age'].agg([max,min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [103]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [105]:
titanic['Cabin']=titanic['Cabin'].fillna('C000')

In [106]:
titanic['Age']=titanic['Age'].fillna(titanic['Age'].mean())

In [107]:
titanic['Embarked']=titanic['Embarked'].fillna('s')

In [108]:
titanic.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [109]:
def get_square(a):
    return a**2

In [110]:
get_square(3)

9

In [111]:
lambda_square=lambda x: x**2

In [112]:
lambda_square(3)

9

In [113]:
titanic['Name_len']=titanic.Name.apply(lambda x: len(x))

In [114]:
titanic[['Name','Name_len']]

Name  Name_len
0                              Braund, Mr. Owen Harris        23
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                               Heikkinen, Miss. Laina        22
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)        44
4                             Allen, Mr. William Henry        24
..                                                 ...       ...
886                              Montvila, Rev. Juozas        21
887                       Graham, Miss. Margaret Edith        28
888           Johnston, Miss. Catherine Helen "Carrie"        40
889                              Behr, Mr. Karl Howell        21
890                                Dooley, Mr. Patrick        19

[891 rows x 2 columns]

In [115]:
titanic['Child_Adult']=titanic.Age.apply(lambda x: 'Child' if x<=15 else 'Adult')

In [117]:
titanic[['Age','Child_Adult']][:10]

Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child
8  27.000000       Adult
9  14.000000       Child

In [118]:
titanic['Age_cat']=titanic.Age.apply(lambda x: 'Child' if x<=15 else ('Adult' if x<=60 else 'Elderly'))

In [121]:
titanic.Age_cat.value_counts()

Adult      786
Child       83
Elderly     22
Name: Age_cat, dtype: int64